Play travis
Otus-DevOps-2021-08/ivasheg_infra pull request #1
Opened 2021-09-14 20:39 UTC by ivasheg

final merge

2021-09-15 09:03 UTC, mrgreyves requested changes
Здравствуйте!) Оставил комментарий к файлу, дз возвращаю на доработку.

2021-09-15 09:03 UTC, mrgreyves commented on play-travis/test.py
> +        self.assertEqual(1 + 1, 1)
Смотрим внимательно на этот файлик =)

2021-09-15 15:41 UTC, ivasheg commented on play-travis/test.py
> +        self.assertEqual(1 + 1, 1)
Из задания не ясно что тест надо исправить чтобы он проходил

2021-09-15 16:00 UTC, ivasheg commented on play-travis/test.py
> +        self.assertEqual(1 + 1, 1)
Исправил, просьба принять =)

2021-09-16 07:57 UTC, mrgreyves commented on play-travis/test.py
> +        self.assertEqual(1 + 1, 1)
Казалось бы, тест красный что-то не так и надо разбираться что же все таки не так =)

2021-09-16 07:57 UTC, mrgreyves approved these changes
Здравствуйте!) Апрув!)

2021-09-16 08:29 UTC, merged